Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Validation;
using WebApplication1.Models;
using System.ComponentModel.DataAnnotations;
using System.Net.Mail;
using System.Net;

namespace WebApplication1.Controllers
{
    public class ManagerController : Controller
    {
        DukoWheelsDBEntities1 db = new DukoWheelsDBEntities1();
        List<UserData> list = new List<UserData>();
        // GET: Manager
        
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ViewAllUsers()
        {
            var users = db.UserDBTables.ToList();
            return View(users);
        }
        public ActionResult Delete(string Email)
        {
            var res = db.UserDBTables.Where(x => x.Email == Email).First();
            db.UserDBTables.Remove(res);
            db.SaveChanges();
            var list = db.UserDBTables.ToList();
            return View("ViewAllUsers", list);
        }
        public ActionResult AddnewUser(UserData data)
        {
            try
            {
                
                    DukoWheelsDBEntities1 db = new DukoWheelsDBEntities1();
                    UserDBTable u = new UserDBTable();
                    u.Name = data.Name;
                    u.Email = data.Email;
                    u.Contact = data.ContactNumber;
                    u.Password = data.Password;
                    u.DateOfBirth = data.DateOfBirth;
                    db.UserDBTables.Add(u);
                    db.SaveChanges();
                
                ModelState.Clear();
                
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        System.Diagnostics.Debug.WriteLine("Hello Rehan");
                        System.Diagnostics.Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
                
            }
            
            return View();
        }

        [HttpPost]
        public ActionResult EditData(UserDBTable data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    DukoWheelsDBEntities1 db = new DukoWheelsDBEntities1();
                    UserDBTable u = new UserDBTable();
                    u.Name = data.Name;
                    u.Email = data.Email;
                    u.Contact = data.Contact;
                    u.Password = data.Password;
                    u.DateOfBirth = data.DateOfBirth;
                    db.Entry(data).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    
                    
                }
                ModelState.Clear();

            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        System.Diagnostics.Debug.WriteLine("Hello Rehan");
                        System.Diagnostics.Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }

            }


            var users = db.UserDBTables.ToList();
            return View("ViewAllUsers", users);
            }

        public ActionResult EditUserForm(UserDBTable data)
        {
            return View();
        }
        public ActionResult Contact(string email,string name,string message, UserDBTable data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var senderEmail = new MailAddress("dukocommunity@gmail.com", "DukoCommunity");
                    var receiverEmail = new MailAddress(email, name);

                    var password = "incredebols@duko";
                    var subject = "DukoWheels";
                    var body = message;
                    var smtp = new SmtpClient
                    {
                        Host = "smtp.gmail.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(senderEmail.Address, password)

                    };
                    using (var mess = new MailMessage(senderEmail, receiverEmail)
                    {
                        Subject = subject,
                        Body = body

                    }
                    )
                    {
                        smtp.Send(mess);
                    }
                }
            }
            catch (Exception)
            {
                ViewBag.Error = "Error";
            }
            return View(data);
        }
    
        public ActionResult VehicleManagement()
        {
            return View();
        }

        public ActionResult UsedCarsSection()
        {
            return View();
        }

        public ActionResult AddUsedCar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddUsedCartoDb(UsedCar data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsedCarsTable u = new UsedCarsTable();
                    //u.Id = data.Id;
                    u.Brand = data.Brand;
                    u.Model = data.Model;
                    u.ManufecturingYear = data.ManufecturingYear;
                    u.Milage = data.Milage;
                    u.Type = data.Type;
                    u.Colour = data.Colour;
                    u.Description = data.Description;
                    u.ImageUrl = data.ImageUrl;
                    u.SellerName = data.SellerName;
                    u.SellerContact = data.SellerContact;
                    db.UsedCarsTables.Add(u);
                    db.SaveChanges();
                }
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        System.Diagnostics.Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
            }
            var usedCars = db.UsedCarsTables.ToList();
            return View("UsedCarsList", usedCars);
        }

        public ActionResult UsedCarsList()
        {
            var usedCars = db.UsedCarsTables.ToList(); 
            return View(usedCars);
        }

        public ActionResult EditUsedCar(UsedCarsTable data)
        {
            return View();
        }

        [HttpPost]
        public ActionResult EditUsedCartoDB(UsedCarsTable data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsedCarsTable u = new UsedCarsTable();
                    u.Id = data.Id;
                    u.Brand = data.Brand;
                    u.Model = data.Model;
                    u.ManufecturingYear = data.ManufecturingYear;
                    u.Milage = data.Milage;
                    u.Type = data.Type;
                    u.Colour = data.Colour;
                    u.Description = data.Description;
                    u.ImageUrl = data.ImageUrl;
                    u.SellerName = data.SellerName;
                    u.SellerContact = data.SellerContact;
                    db.Entry(u).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        System.Diagnostics.Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
            }
            var usedCars = db.UsedCarsTables.ToList();
            return View("UsedCarsList", usedCars);
        }

        public ActionResult DeleteUsedCar(int id)
        {
            var res = db.UsedCarsTables.Where(x => x.Id == id).First();
            db.UsedCarsTables.Remove(res);
            db.SaveChanges();
            var list = db.UsedCarsTables.ToList();
            return View("UsedCarsList", list);
        }
    }
}

Views/Manager/AddUsedCar.cshtml
@model WebApplication1.Models.UsedCar

@{
    ViewBag.Title = "Add Used Car";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Used Car</h2>


@using (Html.BeginForm("AddUsedCartoDb", "Manager", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ManufecturingYear, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ManufecturingYear, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ManufecturingYear, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Colour, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Colour, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Colour, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Milage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Milage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Milage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SellerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SellerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SellerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SellerContact, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SellerContact, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SellerContact, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Manager/AddnewUser.cshtml
@model WebApplication1.Models.UserData
@{
    ViewBag.Title = "AddNewUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .error{
        color:red;
    }
</style>
@using (Html.BeginForm())
{
<div>
    <br />
    <br />
    <div class"form-group">
        <label>Name</label>
        @Html.ValidationMessageFor(model => model.Name,"",new { @class="error"})
        @Html.TextBoxFor(model=>model.Name, new { @class = "form-control" })
    </div>
    <div class"form-group">
        <label>Email</label>
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "error" })
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
    </div>
    <div class"form-group">
        <label>Contact</label>
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "error" })
        @Html.TextBoxFor(model => model.ContactNumber, new { @class = "form-control" })
    </div>
    <div class"form-group">
        <label>Password</label>
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "error" })
        @Html.TextBoxFor(model => model.Password, new { @class = "form-control" })
    </div>
    <div class"form-group">
        <label>DateOfBirth</label>
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "error" })
        @Html.TextBoxFor(model => model.DateOfBirth, new { @class = "form-control" })
    </div>
    <br />
    <div class"form-group">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="reset" class="btn btn-primary">Cancel</button>
    </div>
</div>
}
<br/>
<div>
    @Html.ActionLink("Back to List", "ViewAllUsers")
</div>

Views/Manager/Contact.cshtml
@model WebApplication1.UserDBTable
@{
    ViewBag.Title = "ViewAllUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    <form method="post" action="Contact">
        <br />
        <br />
        <div class="form-horizontal">
            <div class="form-group">

                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">

                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-10">
                <div class="relative">
                    <label for="message" class="leading-7 text-sm text-yellow-500">Message</label>
                    <textarea id="message" name="message" class="form-control"></textarea>
                </div>
            </div>
            <br />
            <div class="p-2 w-full">
                <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </div>
    </form>

}
<div>
    @Html.ActionLink("Back to List", "ViewAllUsers")
</div>

Views/Manager/EditUsedCar.cshtml
@model WebApplication1.UsedCarsTable

@{
    ViewBag.Title = "EditUsedCar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditUsedCar</h2>


@using (Html.BeginForm("EditUsedCartoDB", "Manager", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>UsedCarsTable</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ManufecturingYear, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ManufecturingYear, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ManufecturingYear, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Milage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Milage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Milage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Colour, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Colour, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Colour, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SellerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SellerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SellerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SellerContact, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SellerContact, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SellerContact, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Manager/EditUserForm.cshtml
@model WebApplication1.UserDBTable
@{
    ViewBag.Title = "Application Users";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("EditData", "Manager", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserData</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.HiddenFor(model => model.Email)
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewAllUsers")
</div>

Views/Manager/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ManagerLayout.cshtml";
}

<!--Manager Panel-->
<body>
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex flex-col">
                <div class="h-1 bg-gray-200 rounded overflow-hidden">
                    <div class="w-24 h-full bg-indigo-500"></div>
                </div>
                <div class="flex flex-wrap sm:flex-row flex-col py-6 mb-12">
                    <h1 class="sm:w-2/5 text-gray-900 font-medium title-font text-2xl mb-2 sm:mb-0">Manager DashBord</h1>
                    <p class="sm:w-3/5 leading-relaxed text-base sm:pl-10 pl-0">Automotive managers coordinate transportation and vehicles within their organization, assessing transportation needs and procuring vehicles, parts, and services. ... In this role, automotive managers oversee maintenance, purchasing, and service activities while directing the operations of their departments as a whole.</p>
                </div>
            </div>
            <div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
                <div class="p-4 md:w-1/3 sm:mb-0 mb-6 shadow-md rounded border-2 border-grey-600 ">
                    <div class="rounded-lg h-64 overflow-hidden">
                        <a href=""><img alt="content" class="object-contain object-center h-full w-full" src="~/media/2.jpg"></a>
                    </div>
                    <h2 class="text-xl font-medium title-font text-gray-900 mt-5">User Management</h2>
                    <p class="text-base leading-relaxed mt-2">User management describes the ability for administrators to manage user access to various IT resources like systems, devices, applications, storage systems, networks, SaaS services, and more. ... User management enables admins to control user access and on-board and off-board users to and from IT resources.</p>
                    <a href="/Manager/ViewAllUsers" class="text-indigo-500 inline-flex items-center mt-3">
                        Go to
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
                <div class="p-4 md:w-1/3 sm:mb-0 mb-6 shadow-md rounded border-2 border-grey-600 ">
                    <div class="rounded-lg h-64 overflow-hidden">
                        <a href=""><img alt="content" class="object-contain object-center h-full w-full" src="~/media/3.png"></a>
                    </div>
                    <h2 class="text-xl font-medium title-font text-gray-900 mt-5">Vehicle Management</h2>
                    <p class="text-base leading-relaxed mt-2">Vehicle Management, as described in the first section of this paper, manage the internal health of the vehicle so as to ensure the vehicle components can perform properly, and the use of the vehicle components to perform some goal with respect to its external environment.</p>
                    <a href="/Manager/VehicleManagement" class="text-indigo-500 inline-flex items-center mt-3">
                        Go to
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
                <div class="p-4 md:w-1/3 sm:mb-0 mb-6 shadow-md rounded border-2 border-grey-600 ">
                    <div class="rounded-lg h-64 overflow-hidden">
                        <a href=""><img alt="content" class="object-contain object-center h-full w-full" src="~/media/4.png"></a>
                    </div>
                    <h2 class="text-xl font-medium title-font text-gray-900 mt-5">Orders Management</h2>
                    <p class="text-base leading-relaxed mt-2">list of orders of cars Users requsted for purchasing along with there data.  </p>
                    <a class="text-indigo-500 inline-flex items-center mt-3">
                        Go to
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </section>
</body>

Views/Manager/VehicleManagement.cshtml
@{
    ViewBag.Title = "VehicleManagement";
    Layout = "~/Views/Shared/_ManagerLayout.cshtml";
}

<style>
body { background-image: url('VMCover.jpg'); background-repeat: no-repeat; background-attachment: fixed; background-size: 100% 100%; }
</style>

<body style="background-image: url('../../media/VMCover.jpg'); background-size:cover; background-repeat: no-repeat;">
    <div class="py-20 flex flex-wrap w-full  flex-col items-center text-center">
        <h3 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Vehicle Management</h3>
        <p class="lg:w-1/2 w-full leading-relaxed text-gray-900">Manage the Records of Vehicles Here.</p>
    </div>
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex flex-wrap -mx-4 -mb-10 text-center">
                <div class="sm:w-1/2 mb-10 px-4">
                    <div class="rounded-lg h-64 overflow-hidden">
                        <img alt="content" class="object-cover object-center h-full w-full" src="https://dxsrvil5gxzpy.cloudfront.net/wp-content/uploads/2019/11/07135837/UsedVehicles-Banner-two-silver-cars-and-two-black-cars-with-Red-background.jpg">
                    </div>
                    <h2 class="title-font text-2xl font-medium text-gray-900 mt-6 mb-3">Used Vehicles</h2>
                    <h1 class="leading-relaxed text-2xl text-red-600">Here you manage used vehicles of all makes and models.</h1>
                    <a href="/Manager/UsedCarsList"><button class="flex mx-auto mt-6 text-white bg-red-500 border-0 py-2 px-5 focus:outline-none hover:bg-red-600 rounded">Manage</button></a>
                </div>
                <div class="sm:w-1/2 mb-10 px-4">
                    <div class="rounded-lg h-64 overflow-hidden">
                        <img alt="content" class="object-cover object-center h-full w-full" src="~/media/newVPost.jpg">
                    </div>
                    <h2 class="title-font text-2xl font-medium text-gray-900 mt-6 mb-3">New Vehicles</h2>
                    <h3 class="leading-relaxed text-2xl text-red-600">Here you manage new vehicles of all makes and models.</h3>
                    <button class="flex mx-auto mt-6 text-white bg-red-500 border-0 py-2 px-5 focus:outline-none hover:bg-red-600 rounded">Manage</button>
                </div>
            </div>
        </div>
    </section>
</body>