Controllers/CEOController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CEOController : Controller
    {
        DukoWheelsDBEntities1 db = new DukoWheelsDBEntities1();
        //List<Managers_Data> list = new List<Managers_Data>();
        // GET: CEO
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddManager()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddManagerToDb(Managers_Data data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ManagerDBTable u = new ManagerDBTable();
                    u.Name = data.Name;
                    u.Email = data.Email;
                    u.Contact = data.ContactNumber;
                    u.Password = data.Password;
                    u.DateOfBirth = data.DateOfBirth;
                    u.CNIC_NO = data.CnicNumber;
                    u.BranchName = data.BranchName;
                    db.ManagerDBTables.Add(u);
                    db.SaveChanges();
                }
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        System.Diagnostics.Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
            }
            var DBlist = db.ManagerDBTables.ToList();
            return View("ManagersList", DBlist);
        }

        public ActionResult ManagersList()
        {
            var managers = db.ManagerDBTables.ToList();
            return View(managers);
        }

        [HttpPost]
        public ActionResult EditManagerToDb(ManagerDBTable data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ManagerDBTable u = new ManagerDBTable();
                    u.Name = data.Name;
                    u.Email = data.Email;
                    u.Contact = data.Contact;
                    u.Password = data.Password;
                    u.DateOfBirth = data.DateOfBirth;
                    u.CNIC_NO = data.CNIC_NO;
                    u.BranchName = data.BranchName;
                    db.Entry(u).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        System.Diagnostics.Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
            }
            var list = db.ManagerDBTables.ToList();
            return View("ManagersList", list);
        }
        public ActionResult EditManager(ManagerDBTable model)
        {
            return View();
        }
        public ActionResult DeleteManagerData(String Email)
        {
            var res = db.ManagerDBTables.Where(x => x.Email == Email).First();
            db.ManagerDBTables.Remove(res);
            db.SaveChanges();
            var list = db.ManagerDBTables.ToList();
            return View("ManagersList", list);
        }

        public ActionResult ComplaintsAndReports()
        {
            var CR = db.ContactTables.ToList();
            return View(CR);
        }

        public ActionResult DeleteFeedback(int id)
        {
            var res = db.ContactTables.Where(x => x.Id == id).First();
            db.ContactTables.Remove(res);
            db.SaveChanges();
            var list = db.ContactTables.ToList();
            return View("ComplaintsAndReports", list);
        }

        public ActionResult Sales()
        {
            return View();
        } 
    }
}

Views/CEO/AddManager.cshtml
@model WebApplication1.Models.Managers_Data

@{
    ViewBag.Title = "AddManager";
    Layout = "~/Views/Shared/_CEOLayout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="~/Scripts/DBFunctions.js"></script>
</head>
<body>
    @using (Html.BeginForm("AddManagerToDb", "CEO",FormMethod.Post))
    {
        <section class="text-gray-600 body-font">
            <div class="container mx-auto flex items-center">
                <div class="rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0" style="background-image: url('../../media/logo5.jpeg'); background-size:contain; background-repeat: no-repeat; background-position:center">
                    <h2 class="text-gray-900 text-lg font-medium title-font mb-5">Add new Manager</h2>
                    <div class="relative mb-4">
                        <label for="full-name" class="leading-7 text-sm text-gray-900">Name</label>
                        <input required type="text" id="Name" name="Name" class="w-full bg-transparent rounded border border-gray-300 focus:border-yellow-500 focus:ring-2 focus:ring-yellow-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    <div class="relative mb-4">
                        <label for="dob" class="leading-7 text-sm text-gray-900">Date of Birth</label>
                        <input required type="date" id="DateOfBirth" name="DateOfBirth" class="w-full bg-transparent rounded border border-gray-300 focus:border-yellow-500 focus:ring-2 focus:ring-yellow-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    <div class="relative mb-4">
                        <label for="email" class="leading-7 text-sm text-gray-900">Email Address</label>
                        <input required type="email" id="Email" name="Email" class="w-full bg-transparent rounded border border-gray-300 focus:border-yellow-500 focus:ring-2 focus:ring-yellow-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    <div class="relative mb-4">
                        <label for="password" class="leading-7 text-sm text-gray-900">Password</label>
                        <input required type="password" id="Password" name="Password" class="w-full bg-transparent rounded border border-gray-300 focus:border-yellow-500 focus:ring-2 focus:ring-yellow-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    <div class="relative mb-4">
                        <label for="contactNo" class="leading-7 text-sm text-gray-900">Contact Number</label>
                        <input required type="text" id="ContactNumber" name="ContactNumber" class="w-full bg-transparent rounded border border-gray-300 focus:border-yellow-500 focus:ring-2 focus:ring-yellow-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    <div class="relative mb-4">
                        <label for="cnicNo" class="leading-7 text-sm text-gray-900">CNIC Number</label>
                        <input required type="text" id="CnicNumber" name="CnicNumber" class="w-full bg-transparent rounded border border-gray-300 focus:border-yellow-500 focus:ring-2 focus:ring-yellow-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    <div class="relative mb-4">
                        <label for="branch-name" class="leading-7 text-sm text-gray-900">Branch Name</label>
                        <input required type="text" id="BranchName" name="BranchName" class="w-full bg-transparent rounded border border-gray-300 focus:border-yellow-500 focus:ring-2 focus:ring-yellow-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    <button type="submit" class="text-red-800 text-lg bg-transparent border-2 border-blue-300 py-2 px-8 focus:outline-none hover:bg-yellow-600 rounded text-lg">Add</button>
                </div>
            </div>
        </section>
    }
</body>
</html>

Views/CEO/ComplaintsAndReports.cshtml
@model IEnumerable<WebApplication1.ContactTable>

@{
    ViewBag.Title = "Complaints And FeedBack";
    Layout = "~/Views/Shared/_CEOLayout.cshtml";
}
<body>
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-10 mx-auto">
            <div class="flex flex-col text-center w-full mb-20">
                <h1 class="font-serif title-font mb-4 text-gray-900" style="font-size: xx-large;">~Complaints And Feedback~</h1>
                <p class="lg:w-2/3 mx-auto leading-relaxed text-2xl">View all the suggestion and complaints of Application Users.</p>
            </div>
        </div>
        <div class="container px-5 pb-5 mx-auto">
            <div class="flex flex-wrap -m-4">
                @foreach (var item in Model)
                {
                    <div class="p-4 lg:w-1/3">
                        <div class="h-full bg-gray-100 bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
                            <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">@item.SenderEmail</h2>
                            <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">@item.SenderName</h1>
                            <p class="leading-relaxed mb-3">@item.Message</p><br />
                                @Html.ActionLink("Remove❌", "DeleteFeedback", new {item.Id})
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
</body>

Views/CEO/EditManager.cshtml
@model WebApplication1.ManagerDBTable

@{
    ViewBag.Title = "EditManager";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditManager</h2>


@using (Html.BeginForm("EditManagerToDb", "CEO", FormMethod.Post))
{
    @Html.AntiForgeryToken()
<div class="rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0" style="background-image: url('../../media/logo5.jpeg'); background-size:contain; background-repeat: no-repeat; background-position:center">
    <div class="form-horizontal">
        <h4>Manager's DataBase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.Email)
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BranchName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BranchName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BranchName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CNIC_NO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNIC_NO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CNIC_NO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</div>
        }

        <div>
            @Html.ActionLink("Back to List", "ManagersList")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Views/CEO/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CEOLayout.cshtml";
}

<!-- CEO Panel-->
<body>
    <section class="text-gray-400 body-font bg-gray-900">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex flex-wrap w-full mb-20 flex-col items-center text-center">
                <a href="">
                    <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-white">CEO DashBord </h1>
                </a>
                <p class="lg:w-1/2 w-full leading-relaxed text-opacity-80">Mangers Data manipulation and Application Controls Provided Below </p>
            </div>
            <div class="flex flex-wrap -m-4">
                <div class="xl:w-1/3 md:w-1/2 p-4">
                    <div class="border border-gray-700 border-opacity-75 p-6 rounded-lg">
                        <div class="w-10 h-10 inline-flex items-center justify-center rounded-full bg-gray-800 text-yellow-400 mb-4">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                <circle cx="12" cy="7" r="4"></circle>
                            </svg>

                        </div>
                        <a href="/CEO/ManagersList">
                            <h2 class="text-lg text-white font-medium title-font mb-2">Managers</h2>
                            <p class="leading-relaxed text-base">Manage the data of the managers Along with Viewing the Details</p>
                        </a>
                    </div>
                </div>
                <div class="xl:w-1/3 md:w-1/2 p-4">
                    <div class="border border-gray-700 border-opacity-75 p-6 rounded-lg">
                        <div class="w-10 h-10 inline-flex items-center justify-center rounded-full bg-gray-800 text-yellow-400 mb-4">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>

                        </div>
                        <a href="/CEO/Sales">
                            <h2 class="text-lg text-white font-medium title-font mb-2">Sales</h2>
                            <p class="leading-relaxed text-base">View the Sales progress of the automobile trade relative to Mangers</p>
                        </a>
                    </div>
                </div>
                <div class="xl:w-1/3 md:w-1/2 p-4">
                    <div class="border border-gray-700 border-opacity-75 p-6 rounded-lg">
                        <div class="w-10 h-10 inline-flex items-center justify-center rounded-full bg-gray-800 text-yellow-400 mb-4">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                                <circle cx="6" cy="6" r="3"></circle>
                                <circle cx="6" cy="18" r="3"></circle>
                                <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12"></path>
                            </svg>
                        </div>
                        <a href="/CEO/ComplaintsAndReports">
                            <h2 class="text-lg text-white font-medium title-font mb-2">Complaints and Reports</h2>
                            <p class="leading-relaxed text-base">View all the suggestion and complaints of Application User</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <hr>
    <section class="text-gray-400 bg-gray-900 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex flex-col text-center w-full mb-20">
                <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-white">Application Popularity</h1>
                <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Web application frameworks offer a wide range of pre-written components, code snippets, and whole application templates. We can alter these functions by supplementary code, thus enabling us to create application-specific software specifically designed to assist our needs.</p>
            </div>
            <div class="flex flex-wrap -m-4 text-center">
                <div class="p-4 md:w-1/4 sm:w-1/2 w-full">
                    <div class="border-2 border-gray-800 px-4 py-6 rounded-lg">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-yellow-400 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                            <path d="M8 17l4 4 4-4m-4-5v9"></path>
                            <path d="M20.88 18.09A5 5 0 0018 9h-1.26A8 8 0 103 16.29"></path>
                        </svg>
                        <h2 class="title-font font-medium text-3xl text-white">76.99K</h2>
                        <p class="leading-relaxed">Downloads</p>
                    </div>
                </div>
                <div class="p-4 md:w-1/4 sm:w-1/2 w-full">
                    <div class="border-2 border-gray-800 px-4 py-6 rounded-lg">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-yellow-400 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                            <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"></path>
                            <circle cx="9" cy="7" r="4"></circle>
                            <path d="M23 21v-2a4 4 0 00-3-3.87m-4-12a4 4 0 010 7.75"></path>
                        </svg>
                        <h2 class="title-font font-medium text-3xl text-white">99.76K</h2>
                        <p class="leading-relaxed">Users</p>
                    </div>
                </div>
                <div class="p-4 md:w-1/4 sm:w-1/2 w-full">
                    <div class="border-2 border-gray-800 px-4 py-6 rounded-lg">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-yellow-400 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                            <path d="M3 18v-6a9 9 0 0118 0v6"></path>
                            <path d="M21 19a2 2 0 01-2 2h-1a2 2 0 01-2-2v-3a2 2 0 012-2h3zM3 19a2 2 0 002 2h1a2 2 0 002-2v-3a2 2 0 00-2-2H3z"></path>
                        </svg>
                        <h2 class="title-font font-medium text-3xl text-white">76</h2>
                        <p class="leading-relaxed">Files</p>
                    </div>
                </div>
                <div class="p-4 md:w-1/4 sm:w-1/2 w-full">
                    <div class="border-2 border-gray-800 px-4 py-6 rounded-lg">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-yellow-400 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
                        </svg>
                        <h2 class="title-font font-medium text-3xl text-white">99</h2>
                        <p class="leading-relaxed">Places</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

Views/CEO/ManagersList.cshtml
@model List<WebApplication1.ManagerDBTable>
@{
    ViewBag.Title = "Managers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Company Managers</h2>
<p>
    @Html.ActionLink("Add new Manager", "AddManager")
</p>
<hr />
<p>
    @Html.ActionLink("CEO Main Page", "Index")
</p>
<table class="table table-hover">
    <tr>
        <th>Name</th>
        <th>Date Of Birth</th>
        <th>Email Address</th>
        <th>Password</th>
        <th>Contact No</th>
        <th>Branch Name</th>
        <th>CNIC No</th>
        <th>Action</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.DateOfBirth</td>
            <td>@item.Email</td>
            <td>@item.Password</td>
            <td>@item.Contact</td>
            <td>@item.BranchName</td>
            <td>@item.CNIC_NO</td>
            <td>
                @Html.ActionLink("Edit", "EditManager", new { item.Name,item.Email,item.Password,item.DateOfBirth,item.Contact,item.CNIC_NO,item.BranchName }) |
                @Html.ActionLink("Delete", "DeleteManagerData", new { item.Email })
            </td>
        </tr>
    }
</table>

Views/CEO/Sales.cshtml
@{
    ViewBag.Title = "Sales";
    Layout = "~/Views/Shared/_CEOLayout.cshtml";
}

<h2 class="text-center">Sales</h2>

<hr />

<h4 class="text-center">Page is Under Development....</h4>